services:
  postgres:
    image: postgres:18
    networks:
      - omibot_network
    restart: unless-stopped
    env_file: ".env"
    volumes:
      - ./postgresql:/var/lib/postgresql
  omibot:
    image: ghcr.io/omicron-industries/omibot:latest
    networks:
      - omibot_network
    depends_on:
      - postgres
    restart: unless-stopped
    env_file: ".env"
    environment:
      RUST_LOG: warn
    volumes:
      - ./logs/:/app/logs/
      - ./.env:/app/.env

networks:
  omibot_network:
    driver: bridge
